general:
  train_mode: true
  task: "instance_segmentation"
  seed: 1
  checkpoint: null
  train_on_segments: true
  eval_on_segments: true
  save_visualizations: false
  visualization_point_size: 20
  decoder_id: -1
  export: false
  use_dbscan: false
  ignore_class_threshold: 100
  project_name: scannet
  experiment_name: xxx
  num_targets: 199
  dbscan_eps: 0.95
  dbscan_min_points: 1
  llm_config: ./conf/llm/nollm.json
  llm_data_config: ./conf/llm/det10.json

  filter_scene00: False

  topk_per_image: 100

  save_dir: saved/${general.experiment_name}
  # time/commit/md5(config)_uuid
  # time/experiment_id/version_uuid
  experiment_id: debug # commit[:8], or unique from logger
  version: 1 # md5[:8] of config

  gpus: 1

  timestamp: null

defaults:
  - data: indoor
  - data/data_loaders: simple_loader
  - data/datasets: scannet200
  - data/collation_functions: voxelize_collate
  - logging: offline
  - model: mask3d
  - metrics: miou
  - optimizer: adamw
  - scheduler: onecyclelr
  - trainer: trainer600
  - callbacks: callbacks_instance_segmentation
  - matcher: hungarian_matcher
  - loss: set_criterion
  
hydra:
  run:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${general.save_dir}
    # subdir: ${hydra.job.num}_${hydra.job.id}